@startuml styles

' DEFAULTS
skinparam monochrome false
skinparam backgroundColor #F6F6F6
skinparam handwritten false
' skinparam defaultFontName "Calibri"
' skinparam defaultTextAlignment center

' STYLES
skinparam participant {
  StereotypeFontSize 12
  BackgroundColor #555555
  FontColor white
  ' BackgroundColor #073B6F
  BorderColor #888888
  shadowing false
'   BoxPadding 1000
  ' RoundCorner 20
}

skinparam Arrow {
  Color #666666
  FontColor #666666
  FontSize 12
}

' PARTICIPANTS
hide unlinked
actor Customer
participant Site #purple
participant PIM #purple
participant CoreCustomer #navy
participant CoreProduct #navy
participant CoreLogistics #navy

participant CoreLogistics #navy
participant MessageQueue #maroon
participant NotificationEndpoint #maroon

participant Chargebee #darkgreen
participant Stripe #darkgreen
participant FuturLog  #darkgreen

@enduml