@startuml

' !includeurl https://raw.githubusercontent.com/bmedici/public/master/PlantUML/style.puml?04
!include style.puml

show unlinked
title <&caret-left> Sample PlantUML diagram w/Bruno's styling <&caret-left>

group Customer adjusts bundle contents to its needs
  Customer->Site: increases quantity of P2
  Site<->PIM: exchange prices
  Customer<-Site: updates Cart view and prices
end



activate Site

  Site->CoreCustomer: Validates customer subscription
  note right: Stores customer subscription

  activate CoreCustomer
    CoreCustomer->MessageQueue: <&envelope-closed> customer.subscription.created
    activate MessageQueue
      note right: Stores for processing
      CoreCustomer<--MessageQueue: ACK
    deactivate MessageQueue
  deactivate CoreCustomer
  Site<--CoreCustomer: ACK
deactivate Site

activate MessageQueue
  ' note right: Stores for processing
  MessageQueue->Chargebee: Push Subscrption object update
  note right: Process message
deactivate MessageQueue



' MessageQueue->MessageQueue: <&envelope-open> Process message
' note right: Process message


@enduml